apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lcb-ingress
  namespace: life-command
spec:
  rules:
    - host: lcb.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lcb-web
                port:
                  number: 3000
