export const OBSERVABILITY_EVENT_TYPES = {
  INGESTION_CREATED: "ingestion_created",
  INGESTION_CORRECTED: "ingestion_corrected",
  INGESTION_REJECTED: "ingestion_rejected",

  AUTH_SIGN_IN_STARTED: "auth_sign_in_started",
  AUTH_SIGN_IN_SUCCEEDED: "auth_sign_in_succeeded",
  AUTH_SIGN_IN_FAILED: "auth_sign_in_failed",
  AUTH_SIGN_OUT: "auth_sign_out",
  PROTECTED_ROUTE_REDIRECTED: "protected_route_redirected",

  GMAIL_CONNECTION_CREATED: "gmail_connection_created",
  GMAIL_CONNECTION_LINKED_TO_USER: "gmail_connection_linked_to_user",
  GMAIL_CONNECTION_DISCONNECTED: "gmail_connection_disconnected",
  GMAIL_SYNC_STARTED: "gmail_sync_started",
  GMAIL_SYNC_COMPLETED: "gmail_sync_completed",
  GMAIL_MESSAGE_MATCHED: "gmail_message_matched",
  GMAIL_CANDIDATE_CREATED: "gmail_candidate_created",
  GMAIL_CANDIDATE_REVIEWED: "gmail_candidate_reviewed",
  GMAIL_CANDIDATE_REJECTED: "gmail_candidate_rejected",
  GMAIL_DUPLICATE_SUPPRESSED: "gmail_duplicate_suppressed",
  GMAIL_PREDICTION_STRENGTHENED: "gmail_prediction_strengthened",
  GMAIL_SYNC_ERROR: "gmail_sync_error",
  GMAIL_SUBSCRIPTION_LIFECYCLE_CLASSIFIED: "gmail_subscription_lifecycle_classified",
  GMAIL_SUBSCRIPTION_LIFECYCLE_DETECTED: "gmail_subscription_lifecycle_detected",
  GMAIL_SUBSCRIPTION_AUTO_UPDATED: "gmail_subscription_auto_updated",
  GMAIL_SUBSCRIPTION_CANCELLATION_PROCESSED: "gmail_subscription_cancellation_processed",
  GMAIL_SUBSCRIPTION_CANDIDATE_CREATED: "gmail_subscription_candidate_created",
  GMAIL_SUBSCRIPTION_MATCHED_EXISTING: "gmail_subscription_matched_existing",
  GMAIL_SUBSCRIPTION_CONFLICT_DETECTED: "gmail_subscription_conflict_detected",
  GMAIL_SUBSCRIPTION_CANCELLATION_DETECTED: "gmail_subscription_cancellation_detected",
  GMAIL_SUBSCRIPTION_REVIEW_CONFIRMED: "gmail_subscription_review_confirmed",
  GMAIL_SUBSCRIPTION_REVIEW_REJECTED: "gmail_subscription_review_rejected",
  GMAIL_MESSAGE_CLASSIFIED_V2: "gmail_message_classified_v2",
  GMAIL_VENDOR_MATCHED: "gmail_vendor_matched",
  GMAIL_LIFECYCLE_LINKED: "gmail_lifecycle_linked",
  GMAIL_EXTRACTION_REVIEW: "gmail_extraction_review",
  GMAIL_LLM_FALLBACK_USED: "gmail_llm_fallback_used",
  GMAIL_SUPPRESSED: "gmail_suppressed",

  LLM_CALL_REQUESTED: "llm_call_requested",
  LLM_CALL_SKIPPED_BY_GATE: "llm_call_skipped_by_gate",
  LLM_CACHE_HIT: "llm_cache_hit",
  LLM_CACHE_MISS: "llm_cache_miss",
  LLM_PROVIDER_PROMPT_CACHE_HIT_IF_AVAILABLE: "llm_provider_prompt_cache_hit_if_available",
  LLM_CALL_COMPLETED: "llm_call_completed",
  LLM_CALL_FAILED: "llm_call_failed",
  LLM_BUDGET_SOFT_LIMIT_HIT: "llm_budget_soft_limit_hit",
  LLM_MODEL_ROUTED: "llm_model_routed",
  LLM_ASYNC_TASK_ENQUEUED: "llm_async_task_enqueued",

  VENDOR_PROFILE_MATCHED: "vendor_profile_matched",
  VENDOR_PROFILE_UNKNOWN: "vendor_profile_unknown",
  VENDOR_PROFILE_CONFLICT: "vendor_profile_conflict",
  VENDOR_PROFILE_SUPPRESSED: "vendor_profile_suppressed",

  SUBSCRIPTION_REGISTRY_CREATED: "subscription_registry_created",
  SUBSCRIPTION_REGISTRY_UPDATED: "subscription_registry_updated",
  SUBSCRIPTION_REGISTRY_MERGED: "subscription_registry_merged",
  SUBSCRIPTION_REGISTRY_REVIEW_CONFIRMED: "subscription_registry_review_confirmed",
  SUBSCRIPTION_REGISTRY_REVIEW_REJECTED: "subscription_registry_review_rejected",
  SUBSCRIPTION_LIFECYCLE_TRANSITIONED: "subscription_lifecycle_transitioned",
  SUBSCRIPTION_PRICE_CHANGED: "subscription_price_changed",
  SUBSCRIPTION_CANCELLATION_DETECTED: "subscription_cancellation_detected",
  SUBSCRIPTION_PREDICTION_STRENGTHENED: "subscription_prediction_strengthened",
  SUBSCRIPTION_OBLIGATION_CREATED: "subscription_obligation_created",
  SUBSCRIPTION_INSIGHT_CREATED: "subscription_insight_created",
  SUBSCRIPTION_RECOMMENDATION_GENERATED: "subscription_recommendation_generated",
  SUBSCRIPTION_REVIEW_STARTED: "subscription_review_started",
  SUBSCRIPTION_REVIEW_HUB_LOADED: "subscription_review_hub_loaded",
  SUBSCRIPTION_REVIEW_HUB_EMPTY: "subscription_review_hub_empty",
  SUBSCRIPTION_REVIEW_ITEM_OPENED: "subscription_review_item_opened",
  SUBSCRIPTION_REVIEW_KEEP_SELECTED: "subscription_review_keep_selected",
  SUBSCRIPTION_REVIEW_CANCEL_SELECTED: "subscription_review_cancel_selected",
  SUBSCRIPTION_REVIEW_REMIND_SELECTED: "subscription_review_remind_selected",
  SUBSCRIPTION_REVIEW_DETAILS_OPENED: "subscription_review_details_opened",
  SUBSCRIPTION_REVIEW_COMPLETED: "subscription_review_completed",
  SUBSCRIPTION_REVIEW_GUIDED_FLOW_HANDOFF: "subscription_review_guided_flow_handoff",
  SUBSCRIPTION_DECISION_TAKEN: "subscription_decision_taken",
  SUBSCRIPTION_KEPT: "subscription_kept",
  SUBSCRIPTION_MARKED_FOR_CANCEL: "subscription_marked_for_cancel",
  SUBSCRIPTION_REGISTRY_UPDATE_SKIPPED: "subscription_registry_update_skipped",

  ANCHOR_CREATED: "anchor_created",
  ANCHOR_UPDATED: "anchor_updated",
  ANCHOR_CANCELLED: "anchor_cancelled",
  ANCHOR_SNOOZED: "anchor_snoozed",
  ANCHOR_SURFACED: "anchor_surfaced",
  ANCHOR_ACTION_COMPLETED: "anchor_action_completed",
  ANCHOR_CONFIRMED_BY_GMAIL: "anchor_confirmed_by_gmail",
  ANCHOR_TIMING_REFINED: "anchor_timing_refined",
  ANCHOR_CANDIDATE_SUPPRESSED_BY_DEDUPE: "anchor_candidate_suppressed_by_dedupe",
  ANCHOR_CANDIDATE_MERGED: "anchor_candidate_merged",
  ANCHOR_FALLBACK_USED: "anchor_fallback_used",
  ANCHOR_MATCHING_FAILED: "anchor_matching_failed",
  ANCHOR_MATCHING_AMBIGUOUS: "anchor_matching_ambiguous",

  PREDICTION_CREATED: "prediction_created",
  PREDICTION_CONFIRMED: "prediction_confirmed",
  PREDICTION_DISMISSED: "prediction_dismissed",
  PREDICTION_PROMOTED: "prediction_promoted",

  AUTO_FLOW_TRIGGERED: "auto_flow_triggered",
  AUTO_FLOW_ACCEPTED: "auto_flow_accepted",
  AUTO_FLOW_DISMISSED: "auto_flow_dismissed",

  GUIDED_STARTED: "guided_started",
  GUIDED_STEP_COMPLETED: "guided_step_completed",
  GUIDED_COMPLETED: "guided_completed",
  GUIDED_ABANDONED: "guided_abandoned",

  OBLIGATION_CREATED: "obligation_created",
  OBLIGATION_CANDIDATE_CLASSIFIED: "obligation_candidate_classified",
  OBLIGATION_CANDIDATE_CREATED: "obligation_candidate_created",
  OBLIGATION_CANDIDATE_UPDATED: "obligation_candidate_updated",
  OBLIGATION_CANDIDATE_REVIEW_ROUTED: "obligation_candidate_review_routed",
  OBLIGATION_DUPLICATE_SUPPRESSED: "obligation_duplicate_suppressed",
  OBLIGATION_PRIORITY_ASSIGNED: "obligation_priority_assigned",
  OBLIGATION_UPCOMING_GENERATED: "obligation_upcoming_generated",
  OBLIGATION_CONTROL_TOWER_SURFACED: "obligation_control_tower_surfaced",
  OBLIGATION_COMPLETED: "obligation_completed",
  OBLIGATION_POSTPONED: "obligation_postponed",
  OBLIGATION_DISMISSED: "obligation_dismissed",

  REVIEW_REQUIRED: "review_required",
  REVIEW_CONFIRMED: "review_confirmed",
  REVIEW_REJECTED: "review_rejected",
  CORRECTION_APPLIED: "correction_applied",

  APPROVAL_REQUIRED: "approval_required",
  APPROVAL_APPROVED: "approval_approved",
  APPROVAL_REJECTED: "approval_rejected",

  AUTONOMY_ACTION_EXECUTED: "autonomy_action_executed",
  AUTONOMY_ACTION_UNDONE: "autonomy_action_undone",

  ASSIGNMENT_CHANGED: "assignment_changed",
  ITEM_CLAIMED: "item_claimed",
  ITEM_REASSIGNED: "item_reassigned",

  HOUSEHOLD_INVITE_ACCEPTED: "household_invite_accepted",

  BEHAVIOR_SIGNAL_RECORDED: "behavior_signal_recorded",
  BEHAVIOR_PROFILE_RECOMPUTED: "behavior_profile_recomputed",
  BEHAVIOR_PROFILE_INSUFFICIENT_DATA: "behavior_profile_insufficient_data",
  BEHAVIOR_PROFILE_CHANGED: "behavior_profile_changed",
  PERSONALIZATION_ADJUSTMENT_APPLIED: "personalization_adjustment_applied",
  TODAY_VIEW_PERSONALIZATION_APPLIED: "today_view_personalization_applied",
  TODAY_VIEW_PERSONALIZATION_SKIPPED: "today_view_personalization_skipped",
  ADAPTIVE_MESSAGE_STYLE_APPLIED: "adaptive_message_style_applied",
  REMINDER_STYLE_APPLIED: "reminder_style_applied",
  PERSONALIZATION_FALLBACK_USED: "personalization_fallback_used",
  PERSONALIZATION_ERROR_RECOVERED: "personalization_error_recovered"
} as const;

export type ObservabilityEventType =
  (typeof OBSERVABILITY_EVENT_TYPES)[keyof typeof OBSERVABILITY_EVENT_TYPES];

export const EVENT_TYPE_SET = new Set<string>(Object.values(OBSERVABILITY_EVENT_TYPES));

export type TimeBucket = "DAY" | "WEEK" | "MONTH";

export const TIME_BUCKETS: TimeBucket[] = ["DAY", "WEEK", "MONTH"];
